# Generated by Django 3.1.2 on 2020-10-26 14:02

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_auto_20201026_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(validators=[Store.models.validate_contact_number]),
        ),
    ]
