# Generated by Django 3.1.2 on 2020-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_user_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_file',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
