# Generated by Django 3.1.2 on 2020-10-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20201029_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateClass',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
