# Generated by Django 3.1.2 on 2020-10-30 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_dateclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateClass',
        ),
    ]
