# Generated by Django 3.1.2 on 2020-10-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_delete_dateclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateClass',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
