# Generated by Django 3.1.2 on 2020-10-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_dateclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateclass',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
