# Generated by Django 3.1.2 on 2020-10-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_dateclass_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateClass',
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
